/* RageDisplay_Vulkan — Vulkan renderer backend for ITGmania. */

#include "global.h"
#include "RageDisplay_Vulkan.h"
#include "RageDisplay_Vulkan_Helpers.h"
#include "RageLog.h"
#include "RageMath.h"
#include "RageSurface.h"
#include "RageSurfaceUtils.h"
#include "RageTextureManager.h"
#include "RageUtil.h"
#include "DisplaySpec.h"
#include "LocalizedString.h"
#include "ModelTypes.h"

#include "arch/LowLevelWindow/LowLevelWindow.h"
#include "arch/LowLevelWindow/LowLevelWindow_SDL.h"
#include <SDL3/SDL_vulkan.h>

#include <algorithm>
#include <cstring>
#include <vector>

static LowLevelWindow *g_pWind = nullptr;

// Embedded SPIR-V shader headers (generated by CMake from src/shaders/vulkan/*.vert/*.frag)
#include "sprite_vert.h"
#include "sprite_frag.h"
#include "lit_sprite_vert.h"
#include "lit_sprite_frag.h"
#include "effect_unpremultiply_frag.h"
#include "effect_colorburn_frag.h"
#include "effect_colordodge_frag.h"
#include "effect_vividlight_frag.h"
#include "effect_hardmix_frag.h"
#include "effect_overlay_frag.h"
#include "effect_screen_frag.h"
#include "effect_yuyv422_frag.h"
#include "effect_distancefield_frag.h"

static const int VERTEX_RING_SIZE = 512 * 1024; // 512 KB per frame
static const int STAGING_RING_SIZE = 4 * 1024 * 1024; // 4 MB per frame

static int vk_power_of_two(int input)
{
	int value = 1;
	while (value < input)
		value <<= 1;
	return value;
}

// ====================================================================
// Pixel format descriptors (CPU-side, same as GL3)
// ====================================================================
static const RageDisplay::RagePixelFormatDesc PIXEL_FORMAT_DESC[NUM_RagePixelFormat] = {
	{ 32, {0xFF000000, 0x00FF0000, 0x0000FF00, 0x000000FF} }, // RGBA8
	{ 32, {0x0000FF00, 0x00FF0000, 0xFF000000, 0x000000FF} }, // BGRA8
	{ 16, {0xF000, 0x0F00, 0x00F0, 0x000F} },                 // RGBA4
	{ 16, {0xF800, 0x07C0, 0x003E, 0x0001} },                 // RGB5A1
	{ 16, {0xF800, 0x07C0, 0x003E, 0x0000} },                 // RGB5
	{ 24, {0xFF0000, 0x00FF00, 0x0000FF, 0x000000} },          // RGB8
	{ 8,  {0, 0, 0, 0} },                                      // PAL
	{ 24, {0x0000FF, 0x00FF00, 0xFF0000, 0x000000} },          // BGR8
	{ 16, {0x003E, 0x07C0, 0xF800, 0x0001} },                 // A1BGR5
	{ 16, {0x7C00, 0x03E0, 0x001F, 0x0000} },                 // X1RGB5
};

// ====================================================================
// Validation layer callback
// ====================================================================
#ifdef DEBUG
static VKAPI_ATTR VkBool32 VKAPI_CALL VulkanDebugCallback(
	VkDebugUtilsMessageSeverityFlagBitsEXT severity,
	VkDebugUtilsMessageTypeFlagsEXT /*type*/,
	const VkDebugUtilsMessengerCallbackDataEXT *pCallbackData,
	void * /*pUserData*/)
{
	if (severity & VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT)
		LOG->Warn("Vulkan ERROR: %s", pCallbackData->pMessage);
	else if (severity & VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT)
		LOG->Warn("Vulkan WARN: %s", pCallbackData->pMessage);
	else
		LOG->Info("Vulkan: %s", pCallbackData->pMessage);
	return VK_FALSE;
}
#endif

// ====================================================================
// Constructor / Destructor
// ====================================================================

RageDisplay_Vulkan::RageDisplay_Vulkan()
{
	LOG->Info("RageDisplay_Vulkan::RageDisplay_Vulkan()");
}

RageDisplay_Vulkan::~RageDisplay_Vulkan()
{
	LOG->Info("RageDisplay_Vulkan::~RageDisplay_Vulkan()");

	if (m_ctx.device)
		vkDeviceWaitIdle(m_ctx.device);

	FlushTextureUploads();
	if (m_uploadFence) vkDestroyFence(m_ctx.device, m_uploadFence, nullptr);
	if (m_uploadPool) vkDestroyCommandPool(m_ctx.device, m_uploadPool, nullptr);

	delete g_pWind;
	g_pWind = nullptr;

	// Destroy pipelines
	for (auto &[key, pipeline] : m_pipelineCache)
		vkDestroyPipeline(m_ctx.device, pipeline, nullptr);
	m_pipelineCache.clear();

	// Destroy textures
	for (auto &[handle, tex] : m_textures)
	{
		if (tex.imageView) vkDestroyImageView(m_ctx.device, tex.imageView, nullptr);
		if (tex.image) vmaDestroyImage(m_ctx.allocator, tex.image, tex.allocation);
	}
	m_textures.clear();

	// Destroy render targets
	for (auto &[handle, rt] : m_renderTargets)
	{
		if (rt.framebuffer) vkDestroyFramebuffer(m_ctx.device, rt.framebuffer, nullptr);
		if (rt.depthImageView) vkDestroyImageView(m_ctx.device, rt.depthImageView, nullptr);
		if (rt.depthImage) vmaDestroyImage(m_ctx.allocator, rt.depthImage, rt.depthAllocation);
		if (rt.texture.imageView) vkDestroyImageView(m_ctx.device, rt.texture.imageView, nullptr);
		if (rt.texture.image) vmaDestroyImage(m_ctx.allocator, rt.texture.image, rt.texture.allocation);
	}
	m_renderTargets.clear();

	// Destroy dummy texture
	if (m_dummyTexture.imageView) vkDestroyImageView(m_ctx.device, m_dummyTexture.imageView, nullptr);
	if (m_dummyTexture.image) vmaDestroyImage(m_ctx.allocator, m_dummyTexture.image, m_dummyTexture.allocation);

	// Destroy symmetric quad strip IBO
	if (m_symQuadIBO) vmaDestroyBuffer(m_ctx.allocator, m_symQuadIBO, m_symQuadIBOAlloc);

	// Destroy white color buffer
	if (m_whiteColorBuf) vmaDestroyBuffer(m_ctx.allocator, m_whiteColorBuf, m_whiteColorAlloc);

	// Destroy quad IBO
	if (m_quadIBO) vmaDestroyBuffer(m_ctx.allocator, m_quadIBO, m_quadIBOAlloc);

	// Destroy UBO
	if (m_uboBuffer) vmaDestroyBuffer(m_ctx.allocator, m_uboBuffer, m_uboAlloc);

	// Destroy samplers
	for (auto &s : m_samplers)
		if (s) vkDestroySampler(m_ctx.device, s, nullptr);

	DestroyShaderModules();
	DestroyFrameResources();

	if (m_vkPipelineCache)
		vkDestroyPipelineCache(m_ctx.device, m_vkPipelineCache, nullptr);
	if (m_pipelineLayout)
		vkDestroyPipelineLayout(m_ctx.device, m_pipelineLayout, nullptr);
	if (m_descSetLayoutPerFrame)
		vkDestroyDescriptorSetLayout(m_ctx.device, m_descSetLayoutPerFrame, nullptr);
	if (m_descSetLayoutTexture)
		vkDestroyDescriptorSetLayout(m_ctx.device, m_descSetLayoutTexture, nullptr);

	DestroySwapchain();

	if (m_ctx.renderPass)
		vkDestroyRenderPass(m_ctx.device, m_ctx.renderPass, nullptr);
	if (m_ctx.allocator)
		vmaDestroyAllocator(m_ctx.allocator);
	if (m_ctx.device)
		vkDestroyDevice(m_ctx.device, nullptr);
	if (m_ctx.surface)
		vkDestroySurfaceKHR(m_ctx.instance, m_ctx.surface, nullptr);

#ifdef DEBUG
	if (m_ctx.debugMessenger)
	{
		auto func = (PFN_vkDestroyDebugUtilsMessengerEXT)vkGetInstanceProcAddr(m_ctx.instance, "vkDestroyDebugUtilsMessengerEXT");
		if (func) func(m_ctx.instance, m_ctx.debugMessenger, nullptr);
	}
#endif

	if (m_ctx.instance)
		vkDestroyInstance(m_ctx.instance, nullptr);
}

// ====================================================================
// Init
// ====================================================================

std::string RageDisplay_Vulkan::Init(const VideoModeParams &p, bool bAllowUnacceleratedRenderer)
{
	LOG->Info("RageDisplay_Vulkan::Init()");

	// Tell LLW_SDL to create a Vulkan window
	LowLevelWindow_SDL::SetWindowAPI(LowLevelWindow_SDL::WindowAPI::Vulkan);

	g_pWind = LowLevelWindow::Create();
	if (!g_pWind)
		return "Failed to create LowLevelWindow";

	bool bNewDeviceOut;
	std::string sErr = TryVideoMode(p, bNewDeviceOut);
	if (!sErr.empty())
		return sErr;

	return std::string();
}

std::string RageDisplay_Vulkan::TryVideoMode(const VideoModeParams &p, bool &bNewDeviceOut)
{
	bNewDeviceOut = (m_ctx.device == VK_NULL_HANDLE);

	// Create or resize the SDL window
	g_pWind->TryVideoMode(p, bNewDeviceOut);

	if (m_ctx.device == VK_NULL_HANDLE)
	{
		// First-time init
		if (!CreateInstance()) return "Failed to create Vulkan instance";
		if (!SelectPhysicalDevice()) return "No suitable Vulkan GPU found";
		if (!CreateLogicalDevice()) return "Failed to create Vulkan device";

		// Create VMA allocator
		VmaVulkanFunctions vulkanFunctions = {};
		vulkanFunctions.vkGetInstanceProcAddr = vkGetInstanceProcAddr;
		vulkanFunctions.vkGetDeviceProcAddr = vkGetDeviceProcAddr;

		VmaAllocatorCreateInfo allocatorCI = {};
		allocatorCI.physicalDevice = m_ctx.physicalDevice;
		allocatorCI.device = m_ctx.device;
		allocatorCI.instance = m_ctx.instance;
		allocatorCI.pVulkanFunctions = &vulkanFunctions;
		if (vmaCreateAllocator(&allocatorCI, &m_ctx.allocator) != VK_SUCCESS)
			return "Failed to create VMA allocator";

		if (!CreateRenderPass()) return "Failed to create render pass";
		if (!CreatePipelineLayout()) return "Failed to create pipeline layout";
		if (!CreateShaderModules()) return "Failed to load shaders";
		if (!CreateSamplers()) return "Failed to create samplers";

		// Create a 4-byte white color buffer for model rendering (models
		// have no per-vertex color, so we bind this as a constant).
		{
			uint32_t white = 0xFFFFFFFF;
			VkBufferCreateInfo bufCI = {};
			bufCI.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
			bufCI.size = 4;
			bufCI.usage = VK_BUFFER_USAGE_VERTEX_BUFFER_BIT;
			VmaAllocationCreateInfo allocCI = {};
			allocCI.usage = VMA_MEMORY_USAGE_AUTO;
			allocCI.flags = VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT;
			vmaCreateBuffer(m_ctx.allocator, &bufCI, &allocCI, &m_whiteColorBuf, &m_whiteColorAlloc, nullptr);
			void *mapped;
			vmaMapMemory(m_ctx.allocator, m_whiteColorAlloc, &mapped);
			memcpy(mapped, &white, 4);
			vmaUnmapMemory(m_ctx.allocator, m_whiteColorAlloc);
		}
		if (!CreateFrameResources()) return "Failed to create frame resources";

		// Create pipeline cache
		VkPipelineCacheCreateInfo cacheCI = {};
		cacheCI.sType = VK_STRUCTURE_TYPE_PIPELINE_CACHE_CREATE_INFO;
		vkCreatePipelineCache(m_ctx.device, &cacheCI, nullptr, &m_vkPipelineCache);

		// Create dummy white texture
		{
			uint32_t white = 0xFFFFFFFF;
			VkImageCreateInfo imgCI = {};
			imgCI.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
			imgCI.imageType = VK_IMAGE_TYPE_2D;
			imgCI.format = VK_FORMAT_R8G8B8A8_UNORM;
			imgCI.extent = {1, 1, 1};
			imgCI.mipLevels = 1;
			imgCI.arrayLayers = 1;
			imgCI.samples = VK_SAMPLE_COUNT_1_BIT;
			imgCI.tiling = VK_IMAGE_TILING_OPTIMAL;
			imgCI.usage = VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_SAMPLED_BIT;

			VmaAllocationCreateInfo allocCI = {};
			allocCI.usage = VMA_MEMORY_USAGE_AUTO;
			vmaCreateImage(m_ctx.allocator, &imgCI, &allocCI, &m_dummyTexture.image, &m_dummyTexture.allocation, nullptr);

			VkImageViewCreateInfo viewCI = {};
			viewCI.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
			viewCI.image = m_dummyTexture.image;
			viewCI.viewType = VK_IMAGE_VIEW_TYPE_2D;
			viewCI.format = VK_FORMAT_R8G8B8A8_UNORM;
			viewCI.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
			vkCreateImageView(m_ctx.device, &viewCI, nullptr, &m_dummyTexture.imageView);

			m_dummyTexture.width = 1;
			m_dummyTexture.height = 1;
			m_dummyTexture.format = VK_FORMAT_R8G8B8A8_UNORM;

			// Upload the white pixel via an immediate command
			VkCommandPool tempPool;
			VkCommandPoolCreateInfo poolCI = {};
			poolCI.sType = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO;
			poolCI.queueFamilyIndex = m_ctx.graphicsQueueFamily;
			poolCI.flags = VK_COMMAND_POOL_CREATE_TRANSIENT_BIT;
			vkCreateCommandPool(m_ctx.device, &poolCI, nullptr, &tempPool);

			VkCommandBufferAllocateInfo cmdAI = {};
			cmdAI.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
			cmdAI.commandPool = tempPool;
			cmdAI.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
			cmdAI.commandBufferCount = 1;
			VkCommandBuffer tempCmd;
			vkAllocateCommandBuffers(m_ctx.device, &cmdAI, &tempCmd);

			VkCommandBufferBeginInfo beginInfo = {};
			beginInfo.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
			beginInfo.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
			vkBeginCommandBuffer(tempCmd, &beginInfo);

			// Create tiny staging buffer
			VkBuffer stagingBuf;
			VmaAllocation stagingAlloc;
			VkBufferCreateInfo bufCI = {};
			bufCI.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
			bufCI.size = 4;
			bufCI.usage = VK_BUFFER_USAGE_TRANSFER_SRC_BIT;
			VmaAllocationCreateInfo stagingAllocCI = {};
			stagingAllocCI.usage = VMA_MEMORY_USAGE_AUTO;
			stagingAllocCI.flags = VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT;
			vmaCreateBuffer(m_ctx.allocator, &bufCI, &stagingAllocCI, &stagingBuf, &stagingAlloc, nullptr);
			void *mapped;
			vmaMapMemory(m_ctx.allocator, stagingAlloc, &mapped);
			memcpy(mapped, &white, 4);
			vmaUnmapMemory(m_ctx.allocator, stagingAlloc);

			VulkanUtil::TransitionImageLayout(tempCmd, m_dummyTexture.image,
				VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL);

			VkBufferImageCopy region = {};
			region.imageSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1};
			region.imageExtent = {1, 1, 1};
			vkCmdCopyBufferToImage(tempCmd, stagingBuf, m_dummyTexture.image,
				VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &region);

			VulkanUtil::TransitionImageLayout(tempCmd, m_dummyTexture.image,
				VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL);

			vkEndCommandBuffer(tempCmd);

			VkSubmitInfo submitInfo = {};
			submitInfo.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
			submitInfo.commandBufferCount = 1;
			submitInfo.pCommandBuffers = &tempCmd;
			vkQueueSubmit(m_ctx.graphicsQueue, 1, &submitInfo, VK_NULL_HANDLE);
			vkQueueWaitIdle(m_ctx.graphicsQueue);

			vmaDestroyBuffer(m_ctx.allocator, stagingBuf, stagingAlloc);
			vkDestroyCommandPool(m_ctx.device, tempPool, nullptr);
		}

		// Create UBO ring buffer for lighting data
		{
			VkPhysicalDeviceProperties props;
			vkGetPhysicalDeviceProperties(m_ctx.physicalDevice, &props);
			m_uboAlignment = std::max((uint32_t)sizeof(PerFrameUBOData),
				(uint32_t)props.limits.minUniformBufferOffsetAlignment);
			// Round up to alignment
			m_uboAlignment = (m_uboAlignment + (uint32_t)props.limits.minUniformBufferOffsetAlignment - 1)
				& ~((uint32_t)props.limits.minUniformBufferOffsetAlignment - 1);

			VkBufferCreateInfo bufCI = {};
			bufCI.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
			bufCI.size = m_uboAlignment * UBO_RING_SIZE * VulkanContext::MAX_FRAMES_IN_FLIGHT;
			bufCI.usage = VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT;

			VmaAllocationCreateInfo allocCI = {};
			allocCI.usage = VMA_MEMORY_USAGE_AUTO;
			allocCI.flags = VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT |
			                VMA_ALLOCATION_CREATE_MAPPED_BIT;

			VmaAllocationInfo allocInfo;
			vmaCreateBuffer(m_ctx.allocator, &bufCI, &allocCI, &m_uboBuffer, &m_uboAlloc, &allocInfo);
			m_uboMapped = allocInfo.pMappedData;
		}
	}

	// (Re)create swapchain
	if (!CreateSwapchain()) return "Failed to create swapchain";
	if (!CreateDepthBuffer()) return "Failed to create depth buffer";
	if (!CreateFramebuffers()) return "Failed to create framebuffers";

	return std::string();
}

// ====================================================================
// Instance / Device / Swapchain creation
// ====================================================================

bool RageDisplay_Vulkan::CreateInstance()
{
	VkApplicationInfo appInfo = {};
	appInfo.sType = VK_STRUCTURE_TYPE_APPLICATION_INFO;
	appInfo.pApplicationName = "ITGmania";
	appInfo.applicationVersion = VK_MAKE_VERSION(1, 0, 0);
	appInfo.pEngineName = "Rage";
	appInfo.engineVersion = VK_MAKE_VERSION(1, 0, 0);
	appInfo.apiVersion = VK_API_VERSION_1_3; // 1.3 for extended dynamic state + negative viewport

	// Get SDL-required extensions
	uint32_t sdlExtCount = 0;
	const char *const *sdlExts = SDL_Vulkan_GetInstanceExtensions(&sdlExtCount);
	std::vector<const char *> extensions(sdlExts, sdlExts + sdlExtCount);

	std::vector<const char *> layers;

#ifdef DEBUG
	extensions.push_back(VK_EXT_DEBUG_UTILS_EXTENSION_NAME);
	layers.push_back("VK_LAYER_KHRONOS_validation");
#endif

	VkInstanceCreateInfo ci = {};
	ci.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
	ci.pApplicationInfo = &appInfo;
	ci.enabledExtensionCount = (uint32_t)extensions.size();
	ci.ppEnabledExtensionNames = extensions.data();
	ci.enabledLayerCount = (uint32_t)layers.size();
	ci.ppEnabledLayerNames = layers.data();

	if (vkCreateInstance(&ci, nullptr, &m_ctx.instance) != VK_SUCCESS)
		return false;

#ifdef DEBUG
	// Setup debug messenger
	VkDebugUtilsMessengerCreateInfoEXT debugCI = {};
	debugCI.sType = VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT;
	debugCI.messageSeverity = VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT |
	                          VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT;
	debugCI.messageType = VK_DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT |
	                      VK_DEBUG_UTILS_MESSAGE_TYPE_VALIDATION_BIT_EXT |
	                      VK_DEBUG_UTILS_MESSAGE_TYPE_PERFORMANCE_BIT_EXT;
	debugCI.pfnUserCallback = VulkanDebugCallback;

	auto createFunc = (PFN_vkCreateDebugUtilsMessengerEXT)vkGetInstanceProcAddr(m_ctx.instance, "vkCreateDebugUtilsMessengerEXT");
	if (createFunc)
		createFunc(m_ctx.instance, &debugCI, nullptr, &m_ctx.debugMessenger);
#endif

	// Create surface via SDL
	auto *pWind = dynamic_cast<LowLevelWindow_SDL *>(g_pWind);
	if (!pWind || !SDL_Vulkan_CreateSurface(pWind->GetWindow(), m_ctx.instance, nullptr, &m_ctx.surface))
		return false;

	return true;
}

bool RageDisplay_Vulkan::SelectPhysicalDevice()
{
	uint32_t count = 0;
	vkEnumeratePhysicalDevices(m_ctx.instance, &count, nullptr);
	if (count == 0) return false;

	std::vector<VkPhysicalDevice> devices(count);
	vkEnumeratePhysicalDevices(m_ctx.instance, &count, devices.data());

	for (auto &dev : devices)
	{
		// Find a queue family that supports graphics + present
		uint32_t qfCount = 0;
		vkGetPhysicalDeviceQueueFamilyProperties(dev, &qfCount, nullptr);
		std::vector<VkQueueFamilyProperties> qfProps(qfCount);
		vkGetPhysicalDeviceQueueFamilyProperties(dev, &qfCount, qfProps.data());

		int graphicsFamily = -1, presentFamily = -1;
		for (uint32_t i = 0; i < qfCount; i++)
		{
			if (qfProps[i].queueFlags & VK_QUEUE_GRAPHICS_BIT)
				graphicsFamily = i;

			VkBool32 presentSupport = VK_FALSE;
			vkGetPhysicalDeviceSurfaceSupportKHR(dev, i, m_ctx.surface, &presentSupport);
			if (presentSupport)
				presentFamily = i;
		}

		if (graphicsFamily >= 0 && presentFamily >= 0)
		{
			m_ctx.physicalDevice = dev;
			m_ctx.graphicsQueueFamily = graphicsFamily;
			m_ctx.presentQueueFamily = presentFamily;

			VkPhysicalDeviceProperties props;
			vkGetPhysicalDeviceProperties(dev, &props);
			LOG->Info("Vulkan: Selected GPU: %s", props.deviceName);
			return true;
		}
	}
	return false;
}

bool RageDisplay_Vulkan::CreateLogicalDevice()
{
	std::vector<VkDeviceQueueCreateInfo> queueCIs;
	float priority = 1.0f;

	std::vector<uint32_t> uniqueFamilies = {m_ctx.graphicsQueueFamily};
	if (m_ctx.presentQueueFamily != m_ctx.graphicsQueueFamily)
		uniqueFamilies.push_back(m_ctx.presentQueueFamily);

	for (auto family : uniqueFamilies)
	{
		VkDeviceQueueCreateInfo qCI = {};
		qCI.sType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO;
		qCI.queueFamilyIndex = family;
		qCI.queueCount = 1;
		qCI.pQueuePriorities = &priority;
		queueCIs.push_back(qCI);
	}

	const char *deviceExts[] = {VK_KHR_SWAPCHAIN_EXTENSION_NAME};

	VkPhysicalDeviceFeatures features = {};
	features.fillModeNonSolid = VK_TRUE; // for wireframe

	// Enable Vulkan 1.3 extended dynamic state
	VkPhysicalDeviceVulkan13Features features13 = {};
	features13.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_3_FEATURES;
	features13.dynamicRendering = VK_TRUE;
	features13.synchronization2 = VK_TRUE;

	VkPhysicalDeviceExtendedDynamicStateFeaturesEXT extDynState = {};
	extDynState.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTENDED_DYNAMIC_STATE_FEATURES_EXT;
	extDynState.extendedDynamicState = VK_TRUE;
	extDynState.pNext = &features13;

	VkDeviceCreateInfo ci = {};
	ci.sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO;
	ci.pNext = &extDynState;
	ci.queueCreateInfoCount = (uint32_t)queueCIs.size();
	ci.pQueueCreateInfos = queueCIs.data();
	ci.enabledExtensionCount = 1;
	ci.ppEnabledExtensionNames = deviceExts;
	ci.pEnabledFeatures = &features;

	if (vkCreateDevice(m_ctx.physicalDevice, &ci, nullptr, &m_ctx.device) != VK_SUCCESS)
		return false;

	vkGetDeviceQueue(m_ctx.device, m_ctx.graphicsQueueFamily, 0, &m_ctx.graphicsQueue);
	vkGetDeviceQueue(m_ctx.device, m_ctx.presentQueueFamily, 0, &m_ctx.presentQueue);
	return true;
}

bool RageDisplay_Vulkan::CreateSwapchain()
{
	VkSurfaceCapabilitiesKHR caps;
	vkGetPhysicalDeviceSurfaceCapabilitiesKHR(m_ctx.physicalDevice, m_ctx.surface, &caps);

	uint32_t formatCount;
	vkGetPhysicalDeviceSurfaceFormatsKHR(m_ctx.physicalDevice, m_ctx.surface, &formatCount, nullptr);
	std::vector<VkSurfaceFormatKHR> formats(formatCount);
	vkGetPhysicalDeviceSurfaceFormatsKHR(m_ctx.physicalDevice, m_ctx.surface, &formatCount, formats.data());

	// Prefer BGRA8 SRGB or UNORM
	VkSurfaceFormatKHR chosen = formats[0];
	for (auto &f : formats)
	{
		if (f.format == VK_FORMAT_B8G8R8A8_UNORM)
		{
			chosen = f;
			break;
		}
	}
	m_ctx.swapchainFormat = chosen.format;

	// Extent
	if (caps.currentExtent.width != UINT32_MAX)
	{
		m_ctx.swapchainExtent = caps.currentExtent;
	}
	else
	{
		auto *pWind = dynamic_cast<LowLevelWindow_SDL *>(g_pWind);
		int w, h;
		SDL_GetWindowSizeInPixels(pWind->GetWindow(), &w, &h);
		m_ctx.swapchainExtent.width = std::clamp((uint32_t)w, caps.minImageExtent.width, caps.maxImageExtent.width);
		m_ctx.swapchainExtent.height = std::clamp((uint32_t)h, caps.minImageExtent.height, caps.maxImageExtent.height);
	}

	uint32_t imageCount = caps.minImageCount + 1;
	if (caps.maxImageCount > 0 && imageCount > caps.maxImageCount)
		imageCount = caps.maxImageCount;

	VkSwapchainKHR oldSwapchain = m_ctx.swapchain;

	VkSwapchainCreateInfoKHR ci = {};
	ci.sType = VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR;
	ci.surface = m_ctx.surface;
	ci.minImageCount = imageCount;
	ci.imageFormat = chosen.format;
	ci.imageColorSpace = chosen.colorSpace;
	ci.imageExtent = m_ctx.swapchainExtent;
	ci.imageArrayLayers = 1;
	ci.imageUsage = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT;
	ci.preTransform = caps.currentTransform;
	ci.compositeAlpha = VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR;
	// Select present mode based on vsync preference
	VkPresentModeKHR presentMode = VK_PRESENT_MODE_FIFO_KHR; // vsync on (default)
	if (!g_pWind->GetActualVideoModeParams().vsync)
	{
		// Prefer MAILBOX (low-latency, no tearing) over IMMEDIATE (tearing OK)
		uint32_t presentModeCount;
		vkGetPhysicalDeviceSurfacePresentModesKHR(m_ctx.physicalDevice, m_ctx.surface, &presentModeCount, nullptr);
		std::vector<VkPresentModeKHR> presentModes(presentModeCount);
		vkGetPhysicalDeviceSurfacePresentModesKHR(m_ctx.physicalDevice, m_ctx.surface, &presentModeCount, presentModes.data());

		presentMode = VK_PRESENT_MODE_IMMEDIATE_KHR; // fallback: no vsync
		for (auto mode : presentModes)
		{
			if (mode == VK_PRESENT_MODE_MAILBOX_KHR)
			{
				presentMode = VK_PRESENT_MODE_MAILBOX_KHR;
				break;
			}
		}
		LOG->Info("Vulkan: Vsync off, present mode: %s",
			presentMode == VK_PRESENT_MODE_MAILBOX_KHR ? "mailbox" : "immediate");
	}
	ci.presentMode = presentMode;
	ci.clipped = VK_TRUE;
	ci.oldSwapchain = oldSwapchain;

	if (m_ctx.graphicsQueueFamily != m_ctx.presentQueueFamily)
	{
		uint32_t families[] = {m_ctx.graphicsQueueFamily, m_ctx.presentQueueFamily};
		ci.imageSharingMode = VK_SHARING_MODE_CONCURRENT;
		ci.queueFamilyIndexCount = 2;
		ci.pQueueFamilyIndices = families;
	}
	else
	{
		ci.imageSharingMode = VK_SHARING_MODE_EXCLUSIVE;
	}

	if (vkCreateSwapchainKHR(m_ctx.device, &ci, nullptr, &m_ctx.swapchain) != VK_SUCCESS)
		return false;

	if (oldSwapchain)
	{
		// Destroy old swapchain image views
		for (auto &iv : m_ctx.swapchainImageViews)
			vkDestroyImageView(m_ctx.device, iv, nullptr);
		for (auto &fb : m_ctx.framebuffers)
			vkDestroyFramebuffer(m_ctx.device, fb, nullptr);
		vkDestroySwapchainKHR(m_ctx.device, oldSwapchain, nullptr);
	}

	vkGetSwapchainImagesKHR(m_ctx.device, m_ctx.swapchain, &imageCount, nullptr);
	m_ctx.swapchainImages.resize(imageCount);
	vkGetSwapchainImagesKHR(m_ctx.device, m_ctx.swapchain, &imageCount, m_ctx.swapchainImages.data());

	// Create image views
	m_ctx.swapchainImageViews.resize(imageCount);
	for (uint32_t i = 0; i < imageCount; i++)
	{
		VkImageViewCreateInfo viewCI = {};
		viewCI.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
		viewCI.image = m_ctx.swapchainImages[i];
		viewCI.viewType = VK_IMAGE_VIEW_TYPE_2D;
		viewCI.format = m_ctx.swapchainFormat;
		viewCI.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
		vkCreateImageView(m_ctx.device, &viewCI, nullptr, &m_ctx.swapchainImageViews[i]);
	}

	LOG->Info("Vulkan: Swapchain %ux%u, %u images", m_ctx.swapchainExtent.width, m_ctx.swapchainExtent.height, imageCount);
	return true;
}

void RageDisplay_Vulkan::DestroySwapchain()
{
	for (auto &fb : m_ctx.framebuffers)
		if (fb) vkDestroyFramebuffer(m_ctx.device, fb, nullptr);
	m_ctx.framebuffers.clear();

	for (auto &iv : m_ctx.swapchainImageViews)
		if (iv) vkDestroyImageView(m_ctx.device, iv, nullptr);
	m_ctx.swapchainImageViews.clear();

	if (m_ctx.depthImageView) { vkDestroyImageView(m_ctx.device, m_ctx.depthImageView, nullptr); m_ctx.depthImageView = VK_NULL_HANDLE; }
	if (m_ctx.depthImage) { vmaDestroyImage(m_ctx.allocator, m_ctx.depthImage, m_ctx.depthAllocation); m_ctx.depthImage = VK_NULL_HANDLE; }

	if (m_ctx.swapchain) { vkDestroySwapchainKHR(m_ctx.device, m_ctx.swapchain, nullptr); m_ctx.swapchain = VK_NULL_HANDLE; }
}

bool RageDisplay_Vulkan::CreateRenderPass()
{
	VkAttachmentDescription colorAttach = {};
	colorAttach.format = m_ctx.swapchainFormat;
	colorAttach.samples = VK_SAMPLE_COUNT_1_BIT;
	colorAttach.loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
	colorAttach.storeOp = VK_ATTACHMENT_STORE_OP_STORE;
	colorAttach.stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
	colorAttach.stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
	colorAttach.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
	colorAttach.finalLayout = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR;

	VkAttachmentDescription depthAttach = {};
	depthAttach.format = VK_FORMAT_D16_UNORM;
	depthAttach.samples = VK_SAMPLE_COUNT_1_BIT;
	depthAttach.loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
	depthAttach.storeOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
	depthAttach.stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
	depthAttach.stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
	depthAttach.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
	depthAttach.finalLayout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL;

	VkAttachmentReference colorRef = {0, VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL};
	VkAttachmentReference depthRef = {1, VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL};

	VkSubpassDescription subpass = {};
	subpass.pipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS;
	subpass.colorAttachmentCount = 1;
	subpass.pColorAttachments = &colorRef;
	subpass.pDepthStencilAttachment = &depthRef;

	VkSubpassDependency dep = {};
	dep.srcSubpass = VK_SUBPASS_EXTERNAL;
	dep.dstSubpass = 0;
	dep.srcStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT | VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT;
	dep.dstStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT | VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT;
	dep.srcAccessMask = 0;
	dep.dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT | VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT;

	VkAttachmentDescription attachments[] = {colorAttach, depthAttach};

	VkRenderPassCreateInfo rpCI = {};
	rpCI.sType = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO;
	rpCI.attachmentCount = 2;
	rpCI.pAttachments = attachments;
	rpCI.subpassCount = 1;
	rpCI.pSubpasses = &subpass;
	rpCI.dependencyCount = 1;
	rpCI.pDependencies = &dep;

	return vkCreateRenderPass(m_ctx.device, &rpCI, nullptr, &m_ctx.renderPass) == VK_SUCCESS;
}

bool RageDisplay_Vulkan::CreateDepthBuffer()
{
	// Destroy old if exists
	if (m_ctx.depthImageView) { vkDestroyImageView(m_ctx.device, m_ctx.depthImageView, nullptr); m_ctx.depthImageView = VK_NULL_HANDLE; }
	if (m_ctx.depthImage) { vmaDestroyImage(m_ctx.allocator, m_ctx.depthImage, m_ctx.depthAllocation); m_ctx.depthImage = VK_NULL_HANDLE; }

	VkImageCreateInfo imgCI = {};
	imgCI.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
	imgCI.imageType = VK_IMAGE_TYPE_2D;
	imgCI.format = m_ctx.depthFormat;
	imgCI.extent = {m_ctx.swapchainExtent.width, m_ctx.swapchainExtent.height, 1};
	imgCI.mipLevels = 1;
	imgCI.arrayLayers = 1;
	imgCI.samples = VK_SAMPLE_COUNT_1_BIT;
	imgCI.tiling = VK_IMAGE_TILING_OPTIMAL;
	imgCI.usage = VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT;

	VmaAllocationCreateInfo allocCI = {};
	allocCI.usage = VMA_MEMORY_USAGE_AUTO;
	if (vmaCreateImage(m_ctx.allocator, &imgCI, &allocCI, &m_ctx.depthImage, &m_ctx.depthAllocation, nullptr) != VK_SUCCESS)
		return false;

	VkImageViewCreateInfo viewCI = {};
	viewCI.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
	viewCI.image = m_ctx.depthImage;
	viewCI.viewType = VK_IMAGE_VIEW_TYPE_2D;
	viewCI.format = m_ctx.depthFormat;
	viewCI.subresourceRange = {VK_IMAGE_ASPECT_DEPTH_BIT, 0, 1, 0, 1};
	return vkCreateImageView(m_ctx.device, &viewCI, nullptr, &m_ctx.depthImageView) == VK_SUCCESS;
}

bool RageDisplay_Vulkan::CreateFramebuffers()
{
	m_ctx.framebuffers.resize(m_ctx.swapchainImageViews.size());
	for (size_t i = 0; i < m_ctx.swapchainImageViews.size(); i++)
	{
		VkImageView attachments[] = {m_ctx.swapchainImageViews[i], m_ctx.depthImageView};

		VkFramebufferCreateInfo fbCI = {};
		fbCI.sType = VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO;
		fbCI.renderPass = m_ctx.renderPass;
		fbCI.attachmentCount = 2;
		fbCI.pAttachments = attachments;
		fbCI.width = m_ctx.swapchainExtent.width;
		fbCI.height = m_ctx.swapchainExtent.height;
		fbCI.layers = 1;

		if (vkCreateFramebuffer(m_ctx.device, &fbCI, nullptr, &m_ctx.framebuffers[i]) != VK_SUCCESS)
			return false;
	}
	return true;
}

bool RageDisplay_Vulkan::CreateFrameResources()
{
	for (int i = 0; i < VulkanContext::MAX_FRAMES_IN_FLIGHT; i++)
	{
		auto &f = m_ctx.frames[i];

		// Command pool
		VkCommandPoolCreateInfo poolCI = {};
		poolCI.sType = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO;
		poolCI.queueFamilyIndex = m_ctx.graphicsQueueFamily;
		poolCI.flags = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;
		vkCreateCommandPool(m_ctx.device, &poolCI, nullptr, &f.commandPool);

		// Command buffer
		VkCommandBufferAllocateInfo cmdAI = {};
		cmdAI.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
		cmdAI.commandPool = f.commandPool;
		cmdAI.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
		cmdAI.commandBufferCount = 1;
		vkAllocateCommandBuffers(m_ctx.device, &cmdAI, &f.commandBuffer);

		// Sync objects
		VkSemaphoreCreateInfo semCI = {};
		semCI.sType = VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO;
		vkCreateSemaphore(m_ctx.device, &semCI, nullptr, &f.imageAvailable);
		vkCreateSemaphore(m_ctx.device, &semCI, nullptr, &f.renderFinished);

		VkFenceCreateInfo fenceCI = {};
		fenceCI.sType = VK_STRUCTURE_TYPE_FENCE_CREATE_INFO;
		fenceCI.flags = VK_FENCE_CREATE_SIGNALED_BIT;
		vkCreateFence(m_ctx.device, &fenceCI, nullptr, &f.inFlight);

		// Streaming vertex buffer
		f.vertexCapacity = VERTEX_RING_SIZE;
		VkBufferCreateInfo bufCI = {};
		bufCI.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
		bufCI.size = f.vertexCapacity;
		bufCI.usage = VK_BUFFER_USAGE_VERTEX_BUFFER_BIT;

		VmaAllocationCreateInfo allocCI = {};
		allocCI.usage = VMA_MEMORY_USAGE_AUTO;
		allocCI.flags = VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT | VMA_ALLOCATION_CREATE_MAPPED_BIT;

		VmaAllocationInfo allocInfo;
		vmaCreateBuffer(m_ctx.allocator, &bufCI, &allocCI, &f.vertexBuffer, &f.vertexAllocation, &allocInfo);
		f.vertexMapped = allocInfo.pMappedData;

		// Staging buffer
		f.stagingCapacity = STAGING_RING_SIZE;
		bufCI.size = f.stagingCapacity;
		bufCI.usage = VK_BUFFER_USAGE_TRANSFER_SRC_BIT;
		vmaCreateBuffer(m_ctx.allocator, &bufCI, &allocCI, &f.stagingBuffer, &f.stagingAllocation, &allocInfo);
		f.stagingMapped = allocInfo.pMappedData;

		// Descriptor pool
		VkDescriptorPoolSize poolSizes[] = {
			{VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, 512},
			{VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC, 16},
		};
		VkDescriptorPoolCreateInfo dpCI = {};
		dpCI.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
		dpCI.maxSets = 512;
		dpCI.poolSizeCount = 2;
		dpCI.pPoolSizes = poolSizes;
		vkCreateDescriptorPool(m_ctx.device, &dpCI, nullptr, &f.descriptorPool);
	}
	return true;
}

void RageDisplay_Vulkan::DestroyFrameResources()
{
	for (int i = 0; i < VulkanContext::MAX_FRAMES_IN_FLIGHT; i++)
	{
		auto &f = m_ctx.frames[i];
		if (f.inFlight) vkDestroyFence(m_ctx.device, f.inFlight, nullptr);
		if (f.renderFinished) vkDestroySemaphore(m_ctx.device, f.renderFinished, nullptr);
		if (f.imageAvailable) vkDestroySemaphore(m_ctx.device, f.imageAvailable, nullptr);
		if (f.commandPool) vkDestroyCommandPool(m_ctx.device, f.commandPool, nullptr);
		if (f.vertexBuffer) vmaDestroyBuffer(m_ctx.allocator, f.vertexBuffer, f.vertexAllocation);
		if (f.stagingBuffer) vmaDestroyBuffer(m_ctx.allocator, f.stagingBuffer, f.stagingAllocation);
		if (f.descriptorPool) vkDestroyDescriptorPool(m_ctx.device, f.descriptorPool, nullptr);
	}
}

bool RageDisplay_Vulkan::CreatePipelineLayout()
{
	// Set 0: per-frame UBO (lighting/material)
	{
		VkDescriptorSetLayoutBinding uboBinding = {};
		uboBinding.binding = 0;
		uboBinding.descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC;
		uboBinding.descriptorCount = 1;
		uboBinding.stageFlags = VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT;

		VkDescriptorSetLayoutCreateInfo ci = {};
		ci.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
		ci.bindingCount = 1;
		ci.pBindings = &uboBinding;
		vkCreateDescriptorSetLayout(m_ctx.device, &ci, nullptr, &m_descSetLayoutPerFrame);
	}

	// Set 1: texture sampler
	{
		VkDescriptorSetLayoutBinding texBinding = {};
		texBinding.binding = 0;
		texBinding.descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
		texBinding.descriptorCount = 1;
		texBinding.stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT;

		VkDescriptorSetLayoutCreateInfo ci = {};
		ci.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
		ci.bindingCount = 1;
		ci.pBindings = &texBinding;
		vkCreateDescriptorSetLayout(m_ctx.device, &ci, nullptr, &m_descSetLayoutTexture);
	}

	VkDescriptorSetLayout layouts[] = {m_descSetLayoutPerFrame, m_descSetLayoutTexture};

	VkPushConstantRange pcRange = {};
	pcRange.stageFlags = VK_SHADER_STAGE_VERTEX_BIT;
	pcRange.offset = 0;
	pcRange.size = 128; // 2x mat4

	VkPipelineLayoutCreateInfo ci = {};
	ci.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
	ci.setLayoutCount = 2;
	ci.pSetLayouts = layouts;
	ci.pushConstantRangeCount = 1;
	ci.pPushConstantRanges = &pcRange;

	return vkCreatePipelineLayout(m_ctx.device, &ci, nullptr, &m_pipelineLayout) == VK_SUCCESS;
}

bool RageDisplay_Vulkan::CreateShaderModules()
{
	m_spriteVert = VulkanUtil::CreateShaderModule(m_ctx.device, sprite_vert_spv, sprite_vert_spv_size);
	m_spriteFrag = VulkanUtil::CreateShaderModule(m_ctx.device, sprite_frag_spv, sprite_frag_spv_size);
	m_litSpriteVert = VulkanUtil::CreateShaderModule(m_ctx.device, lit_sprite_vert_spv, lit_sprite_vert_spv_size);
	m_litSpriteFrag = VulkanUtil::CreateShaderModule(m_ctx.device, lit_sprite_frag_spv, lit_sprite_frag_spv_size);

	// Effect shaders — all use sprite vertex shader
	m_effectFrags[EffectMode_Normal] = VK_NULL_HANDLE; // use m_spriteFrag
	m_effectFrags[EffectMode_Unpremultiply] = VulkanUtil::CreateShaderModule(m_ctx.device, effect_unpremultiply_frag_spv, effect_unpremultiply_frag_spv_size);
	m_effectFrags[EffectMode_ColorBurn] = VulkanUtil::CreateShaderModule(m_ctx.device, effect_colorburn_frag_spv, effect_colorburn_frag_spv_size);
	m_effectFrags[EffectMode_ColorDodge] = VulkanUtil::CreateShaderModule(m_ctx.device, effect_colordodge_frag_spv, effect_colordodge_frag_spv_size);
	m_effectFrags[EffectMode_VividLight] = VulkanUtil::CreateShaderModule(m_ctx.device, effect_vividlight_frag_spv, effect_vividlight_frag_spv_size);
	m_effectFrags[EffectMode_HardMix] = VulkanUtil::CreateShaderModule(m_ctx.device, effect_hardmix_frag_spv, effect_hardmix_frag_spv_size);
	m_effectFrags[EffectMode_Overlay] = VulkanUtil::CreateShaderModule(m_ctx.device, effect_overlay_frag_spv, effect_overlay_frag_spv_size);
	m_effectFrags[EffectMode_Screen] = VulkanUtil::CreateShaderModule(m_ctx.device, effect_screen_frag_spv, effect_screen_frag_spv_size);
	m_effectFrags[EffectMode_YUYV422] = VulkanUtil::CreateShaderModule(m_ctx.device, effect_yuyv422_frag_spv, effect_yuyv422_frag_spv_size);
	m_effectFrags[EffectMode_DistanceField] = VulkanUtil::CreateShaderModule(m_ctx.device, effect_distancefield_frag_spv, effect_distancefield_frag_spv_size);

	return m_spriteVert && m_spriteFrag && m_litSpriteVert && m_litSpriteFrag;
}

void RageDisplay_Vulkan::DestroyShaderModules()
{
	auto destroy = [&](VkShaderModule &m) { if (m) { vkDestroyShaderModule(m_ctx.device, m, nullptr); m = VK_NULL_HANDLE; } };
	destroy(m_spriteVert);
	destroy(m_spriteFrag);
	destroy(m_litSpriteVert);
	destroy(m_litSpriteFrag);
	for (auto &e : m_effectFrags)
		destroy(e);
}

bool RageDisplay_Vulkan::CreateSamplers()
{
	for (int wrap = 0; wrap < 2; wrap++)
	{
		for (int linear = 0; linear < 2; linear++)
		{
			VkSamplerCreateInfo ci = {};
			ci.sType = VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO;
			ci.magFilter = linear ? VK_FILTER_LINEAR : VK_FILTER_NEAREST;
			ci.minFilter = linear ? VK_FILTER_LINEAR : VK_FILTER_NEAREST;
			ci.mipmapMode = linear ? VK_SAMPLER_MIPMAP_MODE_LINEAR : VK_SAMPLER_MIPMAP_MODE_NEAREST;
			ci.addressModeU = wrap ? VK_SAMPLER_ADDRESS_MODE_REPEAT : VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
			ci.addressModeV = wrap ? VK_SAMPLER_ADDRESS_MODE_REPEAT : VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
			ci.addressModeW = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
			ci.maxLod = VK_LOD_CLAMP_NONE;

			if (vkCreateSampler(m_ctx.device, &ci, nullptr, &m_samplers[wrap * 2 + linear]) != VK_SUCCESS)
				return false;
		}
	}
	return true;
}

VkSampler RageDisplay_Vulkan::GetSampler(bool wrap, bool linear) const
{
	return m_samplers[(wrap ? 1 : 0) * 2 + (linear ? 1 : 0)];
}

// ====================================================================
// Frame lifecycle
// ====================================================================

bool RageDisplay_Vulkan::BeginFrame()
{
	// Flush any pending texture uploads before starting a new frame
	FlushTextureUploads();

	auto &frame = m_ctx.frames[m_ctx.currentFrame];

	// Wait for this frame's previous work to complete
	vkWaitForFences(m_ctx.device, 1, &frame.inFlight, VK_TRUE, UINT64_MAX);

	// Acquire swapchain image
	VkResult result = vkAcquireNextImageKHR(m_ctx.device, m_ctx.swapchain, UINT64_MAX,
		frame.imageAvailable, VK_NULL_HANDLE, &m_ctx.currentImageIndex);
	if (result == VK_ERROR_OUT_OF_DATE_KHR || result == VK_SUBOPTIMAL_KHR)
	{
		LOG->Info("Vulkan: Swapchain out of date, recreating...");
		vkDeviceWaitIdle(m_ctx.device);
		if (!CreateSwapchain() || !CreateDepthBuffer() || !CreateFramebuffers())
		{
			LOG->Warn("Vulkan: Failed to recreate swapchain");
			return false;
		}
		// Try acquire again with the new swapchain
		result = vkAcquireNextImageKHR(m_ctx.device, m_ctx.swapchain, UINT64_MAX,
			frame.imageAvailable, VK_NULL_HANDLE, &m_ctx.currentImageIndex);
		if (result != VK_SUCCESS)
		{
			LOG->Warn("Vulkan: Acquire failed after swapchain recreate: %d", result);
			return false;
		}
		LOG->Info("Vulkan: Swapchain recreated, acquired image %u", m_ctx.currentImageIndex);
	}

	// Only reset fence after successful acquire — prevents deadlock
	vkResetFences(m_ctx.device, 1, &frame.inFlight);

	// Reset frame resources
	frame.vertexOffset = 0;
	frame.stagingOffset = 0;
	m_uboOffset = m_ctx.currentFrame * UBO_RING_SIZE;
	vkResetDescriptorPool(m_ctx.device, frame.descriptorPool, 0);

	// Begin command buffer
	vkResetCommandBuffer(frame.commandBuffer, 0);
	VkCommandBufferBeginInfo beginInfo = {};
	beginInfo.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
	beginInfo.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
	vkBeginCommandBuffer(frame.commandBuffer, &beginInfo);

	m_ctx.inRenderPass = false;
	m_bPipelineBound = false;

	RageDisplay::BeginFrame();
	return true;
}

void RageDisplay_Vulkan::BeginRenderPass()
{
	if (m_ctx.inRenderPass) return;

	auto &frame = m_ctx.frames[m_ctx.currentFrame];

	VkClearValue clearValues[2] = {};
	clearValues[0].color = {{0.0f, 0.0f, 0.0f, 0.0f}};
	clearValues[1].depthStencil = {1.0f, 0};

	VkRenderPassBeginInfo rpBI = {};
	rpBI.sType = VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO;
	rpBI.renderPass = m_ctx.renderPass;
	rpBI.framebuffer = m_ctx.framebuffers[m_ctx.currentImageIndex];
	rpBI.renderArea.extent = m_ctx.swapchainExtent;
	rpBI.clearValueCount = 2;
	rpBI.pClearValues = clearValues;

	vkCmdBeginRenderPass(frame.commandBuffer, &rpBI, VK_SUBPASS_CONTENTS_INLINE);
	m_ctx.inRenderPass = true;
	m_bPipelineBound = false;

	// Set viewport (with negative height for Y-flip, Vulkan 1.1 / VK_KHR_maintenance1)
	VkViewport viewport = {};
	viewport.x = 0.0f;
	viewport.y = (float)m_ctx.swapchainExtent.height;
	viewport.width = (float)m_ctx.swapchainExtent.width;
	viewport.height = -(float)m_ctx.swapchainExtent.height;
	viewport.minDepth = 0.0f;
	viewport.maxDepth = 1.0f;
	vkCmdSetViewport(frame.commandBuffer, 0, 1, &viewport);

	VkRect2D scissor = {};
	scissor.extent = m_ctx.swapchainExtent;
	vkCmdSetScissor(frame.commandBuffer, 0, 1, &scissor);
}

void RageDisplay_Vulkan::EndRenderPass()
{
	if (!m_ctx.inRenderPass) return;
	auto &frame = m_ctx.frames[m_ctx.currentFrame];
	vkCmdEndRenderPass(frame.commandBuffer);
	m_ctx.inRenderPass = false;
}

void RageDisplay_Vulkan::EndFrame()
{
	auto &frame = m_ctx.frames[m_ctx.currentFrame];

	EndRenderPass();

	vkEndCommandBuffer(frame.commandBuffer);

	// Submit
	VkPipelineStageFlags waitStage = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
	VkSubmitInfo submitInfo = {};
	submitInfo.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
	submitInfo.waitSemaphoreCount = 1;
	submitInfo.pWaitSemaphores = &frame.imageAvailable;
	submitInfo.pWaitDstStageMask = &waitStage;
	submitInfo.commandBufferCount = 1;
	submitInfo.pCommandBuffers = &frame.commandBuffer;
	submitInfo.signalSemaphoreCount = 1;
	submitInfo.pSignalSemaphores = &frame.renderFinished;

	vkQueueSubmit(m_ctx.graphicsQueue, 1, &submitInfo, frame.inFlight);

	// Present
	VkPresentInfoKHR presentInfo = {};
	presentInfo.sType = VK_STRUCTURE_TYPE_PRESENT_INFO_KHR;
	presentInfo.waitSemaphoreCount = 1;
	presentInfo.pWaitSemaphores = &frame.renderFinished;
	presentInfo.swapchainCount = 1;
	presentInfo.pSwapchains = &m_ctx.swapchain;
	presentInfo.pImageIndices = &m_ctx.currentImageIndex;

	vkQueuePresentKHR(m_ctx.presentQueue, &presentInfo);

	FrameLimitBeforeVsync(g_pWind->GetActualVideoModeParams().rate);
	FrameLimitAfterVsync();

	g_pWind->Update();

	m_ctx.currentFrame = (m_ctx.currentFrame + 1) % VulkanContext::MAX_FRAMES_IN_FLIGHT;

	RageDisplay::EndFrame();
}

// ====================================================================
// Pipeline management
// ====================================================================

uint16_t RageDisplay_Vulkan::GetCurrentShaderVariant() const
{
	// Encode: vertex shader (0=sprite, 1=lit) | fragment shader selection | spec constants
	uint16_t variant = 0;

	if (m_bLightingEnabled)
		variant |= (1 << 0); // lit vertex shader

	if (m_curEffectMode != EffectMode_Normal)
	{
		variant |= ((uint16_t)m_curEffectMode << 1); // effect frag (bits 1-4)
		variant |= (1 << 5); // flag: using effect shader
	}
	else
	{
		// Sprite frag specialization constants
		variant |= ((uint16_t)m_curTextureMode << 6);  // bits 6-7
		variant |= (m_bAlphaTestEnabled ? 1 : 0) << 8; // bit 8
		variant |= (m_bTextureEnabled[TextureUnit_1] ? 1 : 0) << 9; // bit 9
	}

	return variant;
}

VulkanPipelineKey RageDisplay_Vulkan::MakeCurrentPipelineKey() const
{
	VulkanPipelineKey key;
	key.shaderVariant = GetCurrentShaderVariant();
	key.blendMode = (uint8_t)m_curBlendMode;
	key.flags = (m_curPolygonMode == POLYGON_LINE ? 1 : 0)
	          | (m_bDrawingModel ? 2 : 0);
	return key;
}

VkPipeline RageDisplay_Vulkan::GetOrCreatePipeline(const VulkanPipelineKey &key)
{
	auto it = m_pipelineCache.find(key);
	if (it != m_pipelineCache.end())
		return it->second;

	// Build pipeline
	bool isLit = (key.shaderVariant & 1);
	bool isEffect = (key.shaderVariant & (1 << 5));

	VkShaderModule vertModule = isLit ? m_litSpriteVert : m_spriteVert;
	VkShaderModule fragModule;

	if (isEffect)
	{
		int effectIdx = (key.shaderVariant >> 1) & 0xF;
		fragModule = m_effectFrags[effectIdx];
		if (!fragModule) fragModule = m_spriteFrag; // fallback
	}
	else if (isLit)
	{
		fragModule = m_litSpriteFrag;
	}
	else
	{
		fragModule = m_spriteFrag;
	}

	// Specialization constants for sprite frag
	struct SpecData { int32_t textureMode; VkBool32 alphaTest; VkBool32 textureEnabled; VkBool32 lightingEnabled; };
	SpecData specData = {};
	specData.textureMode = (key.shaderVariant >> 6) & 0x3;
	specData.alphaTest = (key.shaderVariant >> 8) & 1;
	specData.textureEnabled = (key.shaderVariant >> 9) & 1;
	specData.lightingEnabled = isLit ? VK_TRUE : VK_FALSE;

	VkSpecializationMapEntry specEntries[] = {
		{0, offsetof(SpecData, textureMode), sizeof(int32_t)},
		{1, offsetof(SpecData, alphaTest), sizeof(VkBool32)},
		{2, offsetof(SpecData, textureEnabled), sizeof(VkBool32)},
		{3, offsetof(SpecData, lightingEnabled), sizeof(VkBool32)},
	};

	VkSpecializationInfo specInfo = {};
	specInfo.mapEntryCount = isLit ? 4 : 3;
	specInfo.pMapEntries = specEntries;
	specInfo.dataSize = sizeof(SpecData);
	specInfo.pData = &specData;

	VkPipelineShaderStageCreateInfo stages[2] = {};
	stages[0].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
	stages[0].stage = VK_SHADER_STAGE_VERTEX_BIT;
	stages[0].module = vertModule;
	stages[0].pName = "main";

	stages[1].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
	stages[1].stage = VK_SHADER_STAGE_FRAGMENT_BIT;
	stages[1].module = fragModule;
	stages[1].pName = "main";
	stages[1].pSpecializationInfo = &specInfo;

	// Vertex input layout depends on whether we're drawing sprites or models
	bool isModelFormat = (key.flags & 2);

	// Sprite: single interleaved buffer (pos, normal, color, texcoord)
	VkVertexInputBindingDescription spriteBinding = {};
	spriteBinding.binding = 0;
	spriteBinding.stride = sizeof(RageSpriteVertex);
	spriteBinding.inputRate = VK_VERTEX_INPUT_RATE_VERTEX;

	VkVertexInputAttributeDescription spriteAttrs[4] = {};
	spriteAttrs[0] = {0, 0, VK_FORMAT_R32G32B32_SFLOAT, offsetof(RageSpriteVertex, p)};
	spriteAttrs[1] = {1, 0, VK_FORMAT_R32G32B32_SFLOAT, offsetof(RageSpriteVertex, n)};
	spriteAttrs[2] = {2, 0, VK_FORMAT_R8G8B8A8_UNORM, offsetof(RageSpriteVertex, c)};
	spriteAttrs[3] = {3, 0, VK_FORMAT_R32G32_SFLOAT, offsetof(RageSpriteVertex, t)};

	// Model: separate buffers per attribute (pos, normal, texcoord, constant color)
	VkVertexInputBindingDescription modelBindings[4] = {};
	modelBindings[0] = {0, sizeof(RageVector3), VK_VERTEX_INPUT_RATE_VERTEX};    // position
	modelBindings[1] = {1, sizeof(RageVector3), VK_VERTEX_INPUT_RATE_VERTEX};    // normal
	modelBindings[2] = {2, sizeof(RageVector2), VK_VERTEX_INPUT_RATE_VERTEX};    // texcoord
	modelBindings[3] = {3, 0, VK_VERTEX_INPUT_RATE_INSTANCE};                    // constant white color (stride 0 = same value for all)

	VkVertexInputAttributeDescription modelAttrs[4] = {};
	modelAttrs[0] = {0, 0, VK_FORMAT_R32G32B32_SFLOAT, 0};  // position
	modelAttrs[1] = {1, 1, VK_FORMAT_R32G32B32_SFLOAT, 0};  // normal
	modelAttrs[2] = {2, 3, VK_FORMAT_R8G8B8A8_UNORM, 0};    // color (location 2, binding 3 = white buffer)
	modelAttrs[3] = {3, 2, VK_FORMAT_R32G32_SFLOAT, 0};      // texcoord (location 3)

	VkPipelineVertexInputStateCreateInfo vertexInput = {};
	vertexInput.sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;
	if (isModelFormat)
	{
		vertexInput.vertexBindingDescriptionCount = 4;
		vertexInput.pVertexBindingDescriptions = modelBindings;
		vertexInput.vertexAttributeDescriptionCount = 4;
		vertexInput.pVertexAttributeDescriptions = modelAttrs;
	}
	else
	{
		vertexInput.vertexBindingDescriptionCount = 1;
		vertexInput.pVertexBindingDescriptions = &spriteBinding;
		vertexInput.vertexAttributeDescriptionCount = 4;
		vertexInput.pVertexAttributeDescriptions = spriteAttrs;
	}

	VkPipelineInputAssemblyStateCreateInfo inputAssembly = {};
	inputAssembly.sType = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
	inputAssembly.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;

	VkPipelineViewportStateCreateInfo viewportState = {};
	viewportState.sType = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO;
	viewportState.viewportCount = 1;
	viewportState.scissorCount = 1;

	VkPipelineRasterizationStateCreateInfo rasterizer = {};
	rasterizer.sType = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO;
	rasterizer.polygonMode = (key.flags & 1) ? VK_POLYGON_MODE_LINE : VK_POLYGON_MODE_FILL;
	rasterizer.cullMode = VK_CULL_MODE_NONE; // dynamic
	rasterizer.frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE;
	rasterizer.lineWidth = 1.0f;

	VkPipelineMultisampleStateCreateInfo multisampling = {};
	multisampling.sType = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO;
	multisampling.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT;

	VkPipelineDepthStencilStateCreateInfo depthStencil = {};
	depthStencil.sType = VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO;
	depthStencil.depthTestEnable = VK_TRUE;
	depthStencil.depthWriteEnable = VK_TRUE;
	depthStencil.depthCompareOp = VK_COMPARE_OP_LESS_OR_EQUAL;

	auto blendState = VulkanUtil::GetBlendState((BlendMode)key.blendMode);
	VkPipelineColorBlendAttachmentState colorBlendAttachment = {};
	colorBlendAttachment.blendEnable = VK_TRUE;
	colorBlendAttachment.srcColorBlendFactor = blendState.srcColor;
	colorBlendAttachment.dstColorBlendFactor = blendState.dstColor;
	colorBlendAttachment.colorBlendOp = blendState.colorOp;
	colorBlendAttachment.srcAlphaBlendFactor = blendState.srcAlpha;
	colorBlendAttachment.dstAlphaBlendFactor = blendState.dstAlpha;
	colorBlendAttachment.alphaBlendOp = blendState.alphaOp;
	colorBlendAttachment.colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT |
	                                      VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;

	VkPipelineColorBlendStateCreateInfo colorBlend = {};
	colorBlend.sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
	colorBlend.attachmentCount = 1;
	colorBlend.pAttachments = &colorBlendAttachment;

	VkDynamicState dynamicStates[] = {
		VK_DYNAMIC_STATE_VIEWPORT,
		VK_DYNAMIC_STATE_SCISSOR,
		VK_DYNAMIC_STATE_DEPTH_TEST_ENABLE,
		VK_DYNAMIC_STATE_DEPTH_WRITE_ENABLE,
		VK_DYNAMIC_STATE_DEPTH_COMPARE_OP,
		VK_DYNAMIC_STATE_CULL_MODE,
		VK_DYNAMIC_STATE_DEPTH_BIAS_ENABLE,
		VK_DYNAMIC_STATE_DEPTH_BIAS,
		VK_DYNAMIC_STATE_LINE_WIDTH,
		VK_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY,
	};

	VkPipelineDynamicStateCreateInfo dynamicState = {};
	dynamicState.sType = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO;
	dynamicState.dynamicStateCount = sizeof(dynamicStates) / sizeof(dynamicStates[0]);
	dynamicState.pDynamicStates = dynamicStates;

	VkGraphicsPipelineCreateInfo pipelineCI = {};
	pipelineCI.sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
	pipelineCI.stageCount = 2;
	pipelineCI.pStages = stages;
	pipelineCI.pVertexInputState = &vertexInput;
	pipelineCI.pInputAssemblyState = &inputAssembly;
	pipelineCI.pViewportState = &viewportState;
	pipelineCI.pRasterizationState = &rasterizer;
	pipelineCI.pMultisampleState = &multisampling;
	pipelineCI.pDepthStencilState = &depthStencil;
	pipelineCI.pColorBlendState = &colorBlend;
	pipelineCI.pDynamicState = &dynamicState;
	pipelineCI.layout = m_pipelineLayout;
	pipelineCI.renderPass = m_ctx.renderPass;
	pipelineCI.subpass = 0;

	VkPipeline pipeline = VK_NULL_HANDLE;
	if (vkCreateGraphicsPipelines(m_ctx.device, m_vkPipelineCache, 1, &pipelineCI, nullptr, &pipeline) != VK_SUCCESS)
	{
		LOG->Warn("Vulkan: Failed to create pipeline (variant=%u, blend=%u, flags=%u)",
			key.shaderVariant, key.blendMode, key.flags);
		return VK_NULL_HANDLE;
	}

	m_pipelineCache[key] = pipeline;
	return pipeline;
}

void RageDisplay_Vulkan::BindPipelineForCurrentState()
{
	BeginRenderPass();

	auto key = MakeCurrentPipelineKey();
	if (m_bPipelineBound && key == m_lastBoundKey)
		return;

	VkPipeline pipeline = GetOrCreatePipeline(key);
	if (!pipeline) return;

	auto &frame = m_ctx.frames[m_ctx.currentFrame];
	vkCmdBindPipeline(frame.commandBuffer, VK_PIPELINE_BIND_POINT_GRAPHICS, pipeline);
	m_bPipelineBound = true;
	m_lastBoundKey = key;

	// Apply dynamic state
	VkCullModeFlags cullMode = VK_CULL_MODE_NONE;
	if (m_curCullMode == CULL_BACK) cullMode = VK_CULL_MODE_BACK_BIT;
	else if (m_curCullMode == CULL_FRONT) cullMode = VK_CULL_MODE_FRONT_BIT;
	vkCmdSetCullMode(frame.commandBuffer, cullMode);

	bool depthTestEnabled = (m_curZTestMode != ZTEST_OFF);
	vkCmdSetDepthTestEnable(frame.commandBuffer, depthTestEnabled ? VK_TRUE : VK_FALSE);
	vkCmdSetDepthWriteEnable(frame.commandBuffer, m_bZWrite ? VK_TRUE : VK_FALSE);

	VkCompareOp depthOp = VK_COMPARE_OP_ALWAYS;
	if (m_curZTestMode == ZTEST_WRITE_ON_PASS) depthOp = VK_COMPARE_OP_LESS_OR_EQUAL;
	else if (m_curZTestMode == ZTEST_WRITE_ON_FAIL) depthOp = VK_COMPARE_OP_GREATER;
	vkCmdSetDepthCompareOp(frame.commandBuffer, depthOp);

	if (m_fZBias != 0.0f)
	{
		vkCmdSetDepthBiasEnable(frame.commandBuffer, VK_TRUE);
		vkCmdSetDepthBias(frame.commandBuffer, m_fZBias, 0.0f, 0.0f);
	}
	else
	{
		vkCmdSetDepthBiasEnable(frame.commandBuffer, VK_FALSE);
	}

	vkCmdSetLineWidth(frame.commandBuffer, m_fLineWidth);

	// Bind UBO descriptor set (set 0) — required even if lighting is off
	{
		VkDescriptorSetAllocateInfo allocInfo = {};
		allocInfo.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
		allocInfo.descriptorPool = frame.descriptorPool;
		allocInfo.descriptorSetCount = 1;
		allocInfo.pSetLayouts = &m_descSetLayoutPerFrame;

		VkDescriptorSet uboSet;
		VkResult uboResult = vkAllocateDescriptorSets(m_ctx.device, &allocInfo, &uboSet);
		if (uboResult != VK_SUCCESS)
		{
			LOG->Warn("Vulkan: Failed to allocate UBO descriptor set (result=%d)", uboResult);
			return;
		}

		// Write UBO data
		uint32_t dynamicOffset = m_uboOffset * m_uboAlignment;

		// Fill UBO with current lighting/material state
		PerFrameUBOData *uboData = (PerFrameUBOData *)((uint8_t *)m_uboMapped + dynamicOffset);
		RageMatrix modelView;
		RageMatrixMultiply(&modelView, GetViewTop(), GetWorldTop());
		memcpy(uboData->modelView, &modelView, 64);

		// Use first enabled light (or defaults)
		for (int i = 0; i < 8; i++)
		{
			if (m_Lights[i].enabled)
			{
				uboData->lightDir[0] = m_Lights[i].dir.x;
				uboData->lightDir[1] = m_Lights[i].dir.y;
				uboData->lightDir[2] = m_Lights[i].dir.z;
				uboData->lightDir[3] = 0;
				memcpy(uboData->lightAmbient, &m_Lights[i].ambient, 16);
				memcpy(uboData->lightDiffuse, &m_Lights[i].diffuse, 16);
				memcpy(uboData->lightSpecular, &m_Lights[i].specular, 16);
				break;
			}
		}
		memcpy(uboData->matEmissive, &m_MatEmissive, 16);
		memcpy(uboData->matAmbient, &m_MatAmbient, 16);
		memcpy(uboData->matDiffuse, &m_MatDiffuse, 16);
		memcpy(uboData->matSpecular, &m_MatSpecular, 16);
		uboData->matShininess = m_fMatShininess;

		VkDescriptorBufferInfo bufInfo = {};
		bufInfo.buffer = m_uboBuffer;
		bufInfo.offset = 0;
		bufInfo.range = sizeof(PerFrameUBOData);

		VkWriteDescriptorSet write = {};
		write.sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
		write.dstSet = uboSet;
		write.dstBinding = 0;
		write.descriptorCount = 1;
		write.descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC;
		write.pBufferInfo = &bufInfo;

		vkUpdateDescriptorSets(m_ctx.device, 1, &write, 0, nullptr);

		vkCmdBindDescriptorSets(frame.commandBuffer, VK_PIPELINE_BIND_POINT_GRAPHICS,
			m_pipelineLayout, 0, 1, &uboSet, 1, &dynamicOffset);

		// Advance UBO ring
		m_uboOffset++;
	}
}

void RageDisplay_Vulkan::FlushPushConstants()
{
	auto &frame = m_ctx.frames[m_ctx.currentFrame];

	PushConstants pc;

	// Compose MVP: projection * centering * view * world
	RageMatrix mvp;
	RageMatrixMultiply(&mvp, GetCentering(), GetProjectionTop());
	RageMatrix modelView;
	RageMatrixMultiply(&modelView, GetViewTop(), GetWorldTop());
	RageMatrix combined;
	RageMatrixMultiply(&combined, &mvp, &modelView);
	memcpy(pc.mvp, &combined, 64);

	// Texture matrix
	memcpy(pc.texMatrix, GetTextureTop(), 64);

	vkCmdPushConstants(frame.commandBuffer, m_pipelineLayout,
		VK_SHADER_STAGE_VERTEX_BIT, 0, 128, &pc);
}

void RageDisplay_Vulkan::BindCurrentTexture()
{
	auto &frame = m_ctx.frames[m_ctx.currentFrame];

	VulkanTexture *tex = nullptr;
	if (m_iCurrentTextures[TextureUnit_1] != 0)
	{
		auto it = m_textures.find(m_iCurrentTextures[TextureUnit_1]);
		if (it != m_textures.end())
			tex = &it->second;
	}

	VkImageView view = tex ? tex->imageView : m_dummyTexture.imageView;
	bool wrap = m_bTextureWrapping[TextureUnit_1];
	bool linear = m_bTextureFiltering[TextureUnit_1];
	VkSampler sampler = GetSampler(wrap, linear);

	// Allocate descriptor set for this texture
	VkDescriptorSetAllocateInfo allocInfo = {};
	allocInfo.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
	allocInfo.descriptorPool = frame.descriptorPool;
	allocInfo.descriptorSetCount = 1;
	allocInfo.pSetLayouts = &m_descSetLayoutTexture;

	VkDescriptorSet descSet;
	VkResult dsResult = vkAllocateDescriptorSets(m_ctx.device, &allocInfo, &descSet);
	if (dsResult != VK_SUCCESS)
	{
		LOG->Warn("Vulkan: Failed to allocate texture descriptor set (result=%d)", dsResult);
		return;
	}

	VkDescriptorImageInfo imageInfo = {};
	imageInfo.sampler = sampler;
	imageInfo.imageView = view;
	imageInfo.imageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;

	VkWriteDescriptorSet write = {};
	write.sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
	write.dstSet = descSet;
	write.dstBinding = 0;
	write.descriptorCount = 1;
	write.descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
	write.pImageInfo = &imageInfo;

	vkUpdateDescriptorSets(m_ctx.device, 1, &write, 0, nullptr);

	vkCmdBindDescriptorSets(frame.commandBuffer, VK_PIPELINE_BIND_POINT_GRAPHICS,
		m_pipelineLayout, 1, 1, &descSet, 0, nullptr);
}

void RageDisplay_Vulkan::UploadVertices(const RageSpriteVertex v[], int iNumVerts)
{
	auto &frame = m_ctx.frames[m_ctx.currentFrame];
	uint32_t size = iNumVerts * sizeof(RageSpriteVertex);

	if (frame.vertexOffset + size > frame.vertexCapacity)
	{
		LOG->Warn("Vulkan: Vertex ring buffer overflow (%u + %u > %u)",
			frame.vertexOffset, size, frame.vertexCapacity);
		return;
	}

	memcpy((uint8_t *)frame.vertexMapped + frame.vertexOffset, v, size);

	VkDeviceSize offset = frame.vertexOffset;
	vkCmdBindVertexBuffers(frame.commandBuffer, 0, 1, &frame.vertexBuffer, &offset);

	frame.vertexOffset += size;
}

void RageDisplay_Vulkan::EnsureQuadIBO(int iNumQuads)
{
	if (iNumQuads <= m_iQuadIBOSize)
		return;

	int newSize = std::max(iNumQuads, std::max(m_iQuadIBOSize * 2, 256));

	// Generate index data
	std::vector<uint16_t> indices(newSize * 6);
	for (int i = 0; i < newSize; i++)
	{
		indices[i * 6 + 0] = i * 4 + 0;
		indices[i * 6 + 1] = i * 4 + 1;
		indices[i * 6 + 2] = i * 4 + 2;
		indices[i * 6 + 3] = i * 4 + 0;
		indices[i * 6 + 4] = i * 4 + 2;
		indices[i * 6 + 5] = i * 4 + 3;
	}

	// Destroy old
	if (m_quadIBO)
		vmaDestroyBuffer(m_ctx.allocator, m_quadIBO, m_quadIBOAlloc);

	VkBufferCreateInfo bufCI = {};
	bufCI.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
	bufCI.size = indices.size() * sizeof(uint16_t);
	bufCI.usage = VK_BUFFER_USAGE_INDEX_BUFFER_BIT;

	VmaAllocationCreateInfo allocCI = {};
	allocCI.usage = VMA_MEMORY_USAGE_AUTO;
	allocCI.flags = VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT;

	vmaCreateBuffer(m_ctx.allocator, &bufCI, &allocCI, &m_quadIBO, &m_quadIBOAlloc, nullptr);

	void *mapped;
	vmaMapMemory(m_ctx.allocator, m_quadIBOAlloc, &mapped);
	memcpy(mapped, indices.data(), bufCI.size);
	vmaUnmapMemory(m_ctx.allocator, m_quadIBOAlloc);

	m_iQuadIBOSize = newSize;
}

// ====================================================================
// Draw methods
// ====================================================================

void RageDisplay_Vulkan::DrawQuadsInternal(const RageSpriteVertex v[], int iNumVerts)
{
	if (iNumVerts == 0) return;

	int iNumQuads = iNumVerts / 4;
	EnsureQuadIBO(iNumQuads);

	BindPipelineForCurrentState();
	FlushPushConstants();
	BindCurrentTexture();
	UploadVertices(v, iNumVerts);

	auto &frame = m_ctx.frames[m_ctx.currentFrame];
	vkCmdSetPrimitiveTopology(frame.commandBuffer, VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST);
	vkCmdBindIndexBuffer(frame.commandBuffer, m_quadIBO, 0, VK_INDEX_TYPE_UINT16);
	vkCmdDrawIndexed(frame.commandBuffer, iNumQuads * 6, 1, 0, 0, 0);
}

void RageDisplay_Vulkan::DrawQuadStripInternal(const RageSpriteVertex v[], int iNumVerts)
{
	if (iNumVerts < 4) return;

	BindPipelineForCurrentState();
	FlushPushConstants();
	BindCurrentTexture();
	UploadVertices(v, iNumVerts);

	auto &frame = m_ctx.frames[m_ctx.currentFrame];
	vkCmdSetPrimitiveTopology(frame.commandBuffer, VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP);
	vkCmdDraw(frame.commandBuffer, iNumVerts, 1, 0, 0);
}

void RageDisplay_Vulkan::DrawFanInternal(const RageSpriteVertex v[], int iNumVerts)
{
	if (iNumVerts < 3) return;

	// Convert fan to triangle list (fan topology is optional in Vulkan)
	int iNumTriangles = iNumVerts - 2;
	std::vector<RageSpriteVertex> tris(iNumTriangles * 3);
	for (int i = 0; i < iNumTriangles; i++)
	{
		tris[i * 3 + 0] = v[0];
		tris[i * 3 + 1] = v[i + 1];
		tris[i * 3 + 2] = v[i + 2];
	}

	BindPipelineForCurrentState();
	FlushPushConstants();
	BindCurrentTexture();
	UploadVertices(tris.data(), (int)tris.size());

	auto &frame = m_ctx.frames[m_ctx.currentFrame];
	vkCmdSetPrimitiveTopology(frame.commandBuffer, VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST);
	vkCmdDraw(frame.commandBuffer, (uint32_t)tris.size(), 1, 0, 0);
}

void RageDisplay_Vulkan::DrawStripInternal(const RageSpriteVertex v[], int iNumVerts)
{
	if (iNumVerts < 3) return;

	BindPipelineForCurrentState();
	FlushPushConstants();
	BindCurrentTexture();
	UploadVertices(v, iNumVerts);

	auto &frame = m_ctx.frames[m_ctx.currentFrame];
	vkCmdSetPrimitiveTopology(frame.commandBuffer, VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP);
	vkCmdDraw(frame.commandBuffer, iNumVerts, 1, 0, 0);
}

void RageDisplay_Vulkan::DrawTrianglesInternal(const RageSpriteVertex v[], int iNumVerts)
{
	if (iNumVerts == 0) return;

	BindPipelineForCurrentState();
	FlushPushConstants();
	BindCurrentTexture();
	UploadVertices(v, iNumVerts);

	auto &frame = m_ctx.frames[m_ctx.currentFrame];
	vkCmdSetPrimitiveTopology(frame.commandBuffer, VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST);
	vkCmdDraw(frame.commandBuffer, iNumVerts, 1, 0, 0);
}

void RageDisplay_Vulkan::DrawLineStripInternal(const RageSpriteVertex v[], int iNumVerts, float LineWidth)
{
	if (iNumVerts < 2) return;

	BindPipelineForCurrentState();
	FlushPushConstants();
	BindCurrentTexture();
	UploadVertices(v, iNumVerts);

	auto &frame = m_ctx.frames[m_ctx.currentFrame];
	vkCmdSetLineWidth(frame.commandBuffer, LineWidth);
	vkCmdSetPrimitiveTopology(frame.commandBuffer, VK_PRIMITIVE_TOPOLOGY_LINE_STRIP);
	vkCmdDraw(frame.commandBuffer, iNumVerts, 1, 0, 0);
}

void RageDisplay_Vulkan::EnsureSymQuadIBO(int iNumPieces)
{
	if (iNumPieces <= m_iSymQuadIBOSize)
		return;

	int newSize = std::max(iNumPieces, std::max(m_iSymQuadIBOSize * 2, 64));

	std::vector<uint16_t> indices(newSize * 12);
	for (uint16_t i = 0; i < (uint16_t)newSize; i++)
	{
		indices[i*12+0]  = i*3+1;
		indices[i*12+1]  = i*3+3;
		indices[i*12+2]  = i*3+0;
		indices[i*12+3]  = i*3+1;
		indices[i*12+4]  = i*3+4;
		indices[i*12+5]  = i*3+3;
		indices[i*12+6]  = i*3+1;
		indices[i*12+7]  = i*3+5;
		indices[i*12+8]  = i*3+4;
		indices[i*12+9]  = i*3+1;
		indices[i*12+10] = i*3+2;
		indices[i*12+11] = i*3+5;
	}

	if (m_symQuadIBO)
		vmaDestroyBuffer(m_ctx.allocator, m_symQuadIBO, m_symQuadIBOAlloc);

	VkBufferCreateInfo bufCI = {};
	bufCI.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
	bufCI.size = indices.size() * sizeof(uint16_t);
	bufCI.usage = VK_BUFFER_USAGE_INDEX_BUFFER_BIT;

	VmaAllocationCreateInfo allocCI = {};
	allocCI.usage = VMA_MEMORY_USAGE_AUTO;
	allocCI.flags = VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT;

	vmaCreateBuffer(m_ctx.allocator, &bufCI, &allocCI, &m_symQuadIBO, &m_symQuadIBOAlloc, nullptr);

	void *mapped;
	vmaMapMemory(m_ctx.allocator, m_symQuadIBOAlloc, &mapped);
	memcpy(mapped, indices.data(), bufCI.size);
	vmaUnmapMemory(m_ctx.allocator, m_symQuadIBOAlloc);

	m_iSymQuadIBOSize = newSize;
}

void RageDisplay_Vulkan::DrawSymmetricQuadStripInternal(const RageSpriteVertex v[], int iNumVerts)
{
	if (iNumVerts < 6) return;

	int iNumPieces = (iNumVerts - 3) / 3;
	int iNumTriangles = iNumPieces * 4;
	int iNumIndices = iNumTriangles * 3;

	EnsureSymQuadIBO(iNumPieces);

	BindPipelineForCurrentState();
	FlushPushConstants();
	BindCurrentTexture();
	UploadVertices(v, iNumVerts);

	auto &frame = m_ctx.frames[m_ctx.currentFrame];
	vkCmdSetPrimitiveTopology(frame.commandBuffer, VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST);
	vkCmdBindIndexBuffer(frame.commandBuffer, m_symQuadIBO, 0, VK_INDEX_TYPE_UINT16);
	vkCmdDrawIndexed(frame.commandBuffer, iNumIndices, 1, 0, 0, 0);
}

void RageDisplay_Vulkan::DrawCompiledGeometryInternal(const RageCompiledGeometry *p, int iMeshIndex)
{
	m_bDrawingModel = true;
	m_bPipelineBound = false; // force pipeline rebind for model vertex format

	BindPipelineForCurrentState();
	FlushPushConstants();
	BindCurrentTexture();

	auto &frame = m_ctx.frames[m_ctx.currentFrame];

	// Models are always triangle lists
	vkCmdSetPrimitiveTopology(frame.commandBuffer, VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST);

	// Models don't have per-vertex colors. When lighting is off, the legacy
	// renderer uses material color (diffuse+emissive+ambient) as a fallback.
	// Write the computed color into the vertex ring buffer and bind it.
	VkDeviceSize colorOffset = frame.vertexOffset;
	{
		RageColor c = m_MatDiffuse;
		if (!m_bLightingEnabled)
		{
			c.r = std::min(c.r + m_MatEmissive.r + m_MatAmbient.r, 1.0f);
			c.g = std::min(c.g + m_MatEmissive.g + m_MatAmbient.g, 1.0f);
			c.b = std::min(c.b + m_MatEmissive.b + m_MatAmbient.b, 1.0f);
		}
		// Write as BGRA bytes matching VK_FORMAT_R8G8B8A8_UNORM + shader .zyxw swizzle
		uint8_t color[4] = {
			(uint8_t)(c.b * 255.0f),
			(uint8_t)(c.g * 255.0f),
			(uint8_t)(c.r * 255.0f),
			(uint8_t)(c.a * 255.0f)
		};
		if (frame.vertexOffset + 4 <= frame.vertexCapacity)
		{
			memcpy((uint8_t *)frame.vertexMapped + frame.vertexOffset, color, 4);
			frame.vertexOffset += 4;
		}
	}
	vkCmdBindVertexBuffers(frame.commandBuffer, 3, 1, &frame.vertexBuffer, &colorOffset);

	p->Draw(iMeshIndex);

	m_bDrawingModel = false;
	m_bPipelineBound = false; // force pipeline rebind back to sprite format
}

// ====================================================================
// Texture management
// ====================================================================

uintptr_t RageDisplay_Vulkan::AllocTextureHandle()
{
	return m_nextTextureHandle++;
}

uintptr_t RageDisplay_Vulkan::CreateTexture(RagePixelFormat pixfmt, RageSurface *img, bool bGenerateMipMaps)
{
	int texW = vk_power_of_two(img->w);
	int texH = vk_power_of_two(img->h);

	// All textures stored as VK_FORMAT_B8G8R8A8_UNORM (byte order: B,G,R,A).
	// UpdateTexture blits into a staging surface with matching masks.
	(void)pixfmt;
	VkFormat format = VK_FORMAT_B8G8R8A8_UNORM;

	VkImageCreateInfo imgCI = {};
	imgCI.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
	imgCI.imageType = VK_IMAGE_TYPE_2D;
	imgCI.format = format;
	imgCI.extent = {(uint32_t)texW, (uint32_t)texH, 1};
	imgCI.mipLevels = 1;
	imgCI.arrayLayers = 1;
	imgCI.samples = VK_SAMPLE_COUNT_1_BIT;
	imgCI.tiling = VK_IMAGE_TILING_OPTIMAL;
	imgCI.usage = VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_SAMPLED_BIT;

	VmaAllocationCreateInfo allocCI = {};
	allocCI.usage = VMA_MEMORY_USAGE_AUTO;

	VulkanTexture tex;
	tex.format = format;
	tex.width = texW;
	tex.height = texH;
	tex.hasMipmaps = bGenerateMipMaps;

	if (vmaCreateImage(m_ctx.allocator, &imgCI, &allocCI, &tex.image, &tex.allocation, nullptr) != VK_SUCCESS)
	{
		LOG->Warn("Vulkan: Failed to create texture image %dx%d", texW, texH);
		return 0;
	}

	VkImageViewCreateInfo viewCI = {};
	viewCI.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
	viewCI.image = tex.image;
	viewCI.viewType = VK_IMAGE_VIEW_TYPE_2D;
	viewCI.format = format;
	viewCI.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
	vkCreateImageView(m_ctx.device, &viewCI, nullptr, &tex.imageView);

	uintptr_t handle = AllocTextureHandle();
	m_textures[handle] = tex;

	// Upload pixel data
	if (img->pixels)
		UpdateTexture(handle, img, 0, 0, img->w, img->h);

	return handle;
}

void RageDisplay_Vulkan::UpdateTexture(uintptr_t iTexHandle, RageSurface *img,
	int xoffset, int yoffset, int width, int height)
{
	auto it = m_textures.find(iTexHandle);
	if (it == m_textures.end()) return;

	auto &tex = it->second;
	uint32_t uploadSize = width * height * 4;

	// Create a staging buffer for this upload
	VkBuffer stagingBuf;
	VmaAllocation stagingAlloc;
	VkBufferCreateInfo bufCI = {};
	bufCI.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
	bufCI.size = uploadSize;
	bufCI.usage = VK_BUFFER_USAGE_TRANSFER_SRC_BIT;

	VmaAllocationCreateInfo stagingAllocCI = {};
	stagingAllocCI.usage = VMA_MEMORY_USAGE_AUTO;
	stagingAllocCI.flags = VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT |
	                       VMA_ALLOCATION_CREATE_MAPPED_BIT;

	VmaAllocationInfo allocInfo;
	vmaCreateBuffer(m_ctx.allocator, &bufCI, &stagingAllocCI, &stagingBuf, &stagingAlloc, &allocInfo);

	// Create staging surface matching VK_FORMAT_B8G8R8A8_UNORM byte order.
	// On little-endian: byte[0]=B, byte[1]=G, byte[2]=R, byte[3]=A
	// Masks: R=0x00FF0000, G=0x0000FF00, B=0x000000FF, A=0xFF000000
	// Pre-fill with alpha=0xFF so RGB sources without alpha get opaque pixels.
	memset(allocInfo.pMappedData, 0xFF, uploadSize);
	RageSurface *staging = CreateSurfaceFrom(
		width, height, 32,
		0x00FF0000, 0x0000FF00, 0x000000FF, 0xFF000000,
		(uint8_t *)allocInfo.pMappedData, width * 4);
	if (staging)
	{
		RageSurfaceUtils::Blit(img, staging, width, height);
		delete staging;
	}

	// Batch into the pending upload command buffer
	if (!m_uploadCmd)
	{
		// Create a reusable command pool if needed
		if (!m_uploadPool)
		{
			VkCommandPoolCreateInfo poolCI = {};
			poolCI.sType = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO;
			poolCI.queueFamilyIndex = m_ctx.graphicsQueueFamily;
			poolCI.flags = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;
			vkCreateCommandPool(m_ctx.device, &poolCI, nullptr, &m_uploadPool);

			VkCommandBufferAllocateInfo cmdAI = {};
			cmdAI.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
			cmdAI.commandPool = m_uploadPool;
			cmdAI.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
			cmdAI.commandBufferCount = 1;
			vkAllocateCommandBuffers(m_ctx.device, &cmdAI, &m_uploadCmdBuf);

			VkFenceCreateInfo fenceCI = {};
			fenceCI.sType = VK_STRUCTURE_TYPE_FENCE_CREATE_INFO;
			vkCreateFence(m_ctx.device, &fenceCI, nullptr, &m_uploadFence);
		}

		// Begin recording
		vkResetCommandBuffer(m_uploadCmdBuf, 0);
		VkCommandBufferBeginInfo beginInfo = {};
		beginInfo.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
		beginInfo.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
		vkBeginCommandBuffer(m_uploadCmdBuf, &beginInfo);
		m_uploadCmd = true;
	}

	VulkanUtil::TransitionImageLayout(m_uploadCmdBuf, tex.image,
		VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL);

	VkBufferImageCopy region = {};
	region.bufferOffset = 0;
	region.imageSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1};
	region.imageOffset = {xoffset, yoffset, 0};
	region.imageExtent = {(uint32_t)width, (uint32_t)height, 1};

	vkCmdCopyBufferToImage(m_uploadCmdBuf, stagingBuf, tex.image,
		VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &region);

	VulkanUtil::TransitionImageLayout(m_uploadCmdBuf, tex.image,
		VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL);

	// Track staging buffer for cleanup after flush
	m_pendingStagingBuffers.push_back({stagingBuf, stagingAlloc});

	// Always flush immediately — the engine expects textures to be usable
	// right after CreateTexture/UpdateTexture returns
	FlushTextureUploads();
}

void RageDisplay_Vulkan::FlushTextureUploads()
{
	if (!m_uploadCmd || m_pendingStagingBuffers.empty())
		return;

	vkEndCommandBuffer(m_uploadCmdBuf);

	vkResetFences(m_ctx.device, 1, &m_uploadFence);

	VkSubmitInfo submitInfo = {};
	submitInfo.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
	submitInfo.commandBufferCount = 1;
	submitInfo.pCommandBuffers = &m_uploadCmdBuf;
	vkQueueSubmit(m_ctx.graphicsQueue, 1, &submitInfo, m_uploadFence);
	vkWaitForFences(m_ctx.device, 1, &m_uploadFence, VK_TRUE, UINT64_MAX);

	// Clean up staging buffers
	for (auto &[buf, alloc] : m_pendingStagingBuffers)
		vmaDestroyBuffer(m_ctx.allocator, buf, alloc);
	m_pendingStagingBuffers.clear();

	m_uploadCmd = false;
}

void RageDisplay_Vulkan::DeleteTexture(uintptr_t iTexHandle)
{
	auto it = m_textures.find(iTexHandle);
	if (it == m_textures.end()) return;

	// Flush pending uploads that might reference this texture
	FlushTextureUploads();
	vkDeviceWaitIdle(m_ctx.device);

	auto &tex = it->second;
	if (tex.imageView) vkDestroyImageView(m_ctx.device, tex.imageView, nullptr);
	if (tex.image) vmaDestroyImage(m_ctx.allocator, tex.image, tex.allocation);
	m_textures.erase(it);
}

// ====================================================================
// Render state
// ====================================================================

void RageDisplay_Vulkan::SetBlendMode(BlendMode mode)
{
	m_curBlendMode = mode;
	m_bPipelineBound = false; // pipeline key changed
}

void RageDisplay_Vulkan::SetZWrite(bool b)
{
	m_bZWrite = b;
}

void RageDisplay_Vulkan::SetZBias(float f)
{
	m_fZBias = f;
}

void RageDisplay_Vulkan::SetZTestMode(ZTestMode mode)
{
	m_curZTestMode = mode;
}

void RageDisplay_Vulkan::ClearZBuffer()
{
	if (!m_ctx.inRenderPass) return;

	auto &frame = m_ctx.frames[m_ctx.currentFrame];
	VkClearAttachment clearAttach = {};
	clearAttach.aspectMask = VK_IMAGE_ASPECT_DEPTH_BIT;
	clearAttach.clearValue.depthStencil = {1.0f, 0};

	VkClearRect clearRect = {};
	clearRect.rect.extent = m_ctx.swapchainExtent;
	clearRect.layerCount = 1;

	vkCmdClearAttachments(frame.commandBuffer, 1, &clearAttach, 1, &clearRect);
}

void RageDisplay_Vulkan::SetCullMode(CullMode mode)
{
	m_curCullMode = mode;
}

void RageDisplay_Vulkan::SetAlphaTest(bool b)
{
	if (m_bAlphaTestEnabled != b)
	{
		m_bAlphaTestEnabled = b;
		m_bPipelineBound = false; // pipeline key changed
	}
}

void RageDisplay_Vulkan::SetMaterial(
	const RageColor &emissive,
	const RageColor &ambient,
	const RageColor &diffuse,
	const RageColor &specular,
	float shininess)
{
	m_MatEmissive = emissive;
	m_MatAmbient = ambient;
	m_MatDiffuse = diffuse;
	m_MatSpecular = specular;
	m_fMatShininess = shininess;
}

void RageDisplay_Vulkan::SetLighting(bool b)
{
	if (m_bLightingEnabled != b)
	{
		m_bLightingEnabled = b;
		m_bPipelineBound = false; // shader variant changed
	}
}

void RageDisplay_Vulkan::SetLightOff(int index)
{
	if (index >= 0 && index < 8)
		m_Lights[index].enabled = false;
}

void RageDisplay_Vulkan::SetLightDirectional(
	int index,
	const RageColor &ambient,
	const RageColor &diffuse,
	const RageColor &specular,
	const RageVector3 &dir)
{
	if (index < 0 || index >= 8) return;
	m_Lights[index].enabled = true;
	m_Lights[index].ambient = ambient;
	m_Lights[index].diffuse = diffuse;
	m_Lights[index].specular = specular;
	m_Lights[index].dir = dir;
}

void RageDisplay_Vulkan::SetTexture(TextureUnit tu, uintptr_t iTexture)
{
	m_iCurrentTextures[tu] = iTexture;
	m_bTextureEnabled[tu] = (iTexture != 0);
	if (tu == TextureUnit_1)
		m_bPipelineBound = false; // texture enabled state affects pipeline
}

void RageDisplay_Vulkan::SetTextureMode(TextureUnit tu, TextureMode tm)
{
	if (tu == TextureUnit_1 && m_curTextureMode != tm)
	{
		m_curTextureMode = tm;
		m_bPipelineBound = false; // spec constant changed
	}
}

void RageDisplay_Vulkan::SetTextureWrapping(TextureUnit tu, bool b)
{
	m_bTextureWrapping[tu] = b;
}

void RageDisplay_Vulkan::SetTextureFiltering(TextureUnit tu, bool b)
{
	m_bTextureFiltering[tu] = b;
}

void RageDisplay_Vulkan::SetEffectMode(EffectMode effect)
{
	if (m_curEffectMode != effect)
	{
		m_curEffectMode = effect;
		m_bPipelineBound = false; // shader variant changed
	}
}

bool RageDisplay_Vulkan::IsEffectModeSupported(EffectMode effect)
{
	if (effect == EffectMode_Normal) return true;
	return m_effectFrags[effect] != VK_NULL_HANDLE;
}

void RageDisplay_Vulkan::SetSphereEnvironmentMapping(TextureUnit /*tu*/, bool /*b*/)
{
	// TODO: implement if needed
}

void RageDisplay_Vulkan::SetCelShaded(int /*stage*/)
{
	// TODO: implement if needed
}

void RageDisplay_Vulkan::SetPolygonMode(PolygonMode pm)
{
	if (m_curPolygonMode != pm)
	{
		m_curPolygonMode = pm;
		m_bPipelineBound = false;
	}
}

void RageDisplay_Vulkan::SetLineWidth(float fWidth)
{
	m_fLineWidth = fWidth;
}

// ====================================================================
// Texture queries / misc
// ====================================================================

void RageDisplay_Vulkan::ClearAllTextures()
{
	for (int i = 0; i < NUM_TextureUnit; i++)
	{
		m_iCurrentTextures[i] = 0;
		m_bTextureEnabled[i] = false;
	}
}

int RageDisplay_Vulkan::GetNumTextureUnits()
{
	return NUM_TextureUnit;
}

int RageDisplay_Vulkan::GetMaxTextureSize() const
{
	VkPhysicalDeviceProperties props;
	vkGetPhysicalDeviceProperties(m_ctx.physicalDevice, &props);
	return props.limits.maxImageDimension2D;
}

bool RageDisplay_Vulkan::SupportsTextureFormat(RagePixelFormat pixfmt, bool /*realtime*/)
{
	return pixfmt != RagePixelFormat_PAL;
}

bool RageDisplay_Vulkan::SupportsPerVertexMatrixScale()
{
	return false;
}

bool RageDisplay_Vulkan::SupportsRenderToTexture() const
{
	return true;
}

bool RageDisplay_Vulkan::SupportsFullscreenBorderlessWindow() const
{
	return true;
}

bool RageDisplay_Vulkan::IsZWriteEnabled() const
{
	return m_bZWrite;
}

bool RageDisplay_Vulkan::IsZTestEnabled() const
{
	return m_curZTestMode != ZTEST_OFF;
}

const RageDisplay::RagePixelFormatDesc *RageDisplay_Vulkan::GetPixelFormatDesc(RagePixelFormat pf) const
{
	ASSERT(pf >= 0 && pf < NUM_RagePixelFormat);
	return &PIXEL_FORMAT_DESC[pf];
}

void RageDisplay_Vulkan::GetDisplaySpecs(DisplaySpecs &out) const
{
	g_pWind->GetDisplaySpecs(out);
}

ActualVideoModeParams RageDisplay_Vulkan::GetActualVideoModeParams() const
{
	return g_pWind->GetActualVideoModeParams();
}

void RageDisplay_Vulkan::ResolutionChanged()
{
	// Recreate swapchain on resolution change
}

// ====================================================================
// Render targets (stub for now)
// ====================================================================

uintptr_t RageDisplay_Vulkan::CreateRenderTarget(const RenderTargetParam &param, int &iTextureWidthOut, int &iTextureHeightOut)
{
	// TODO: implement render-to-texture
	iTextureWidthOut = vk_power_of_two(param.iWidth);
	iTextureHeightOut = vk_power_of_two(param.iHeight);
	return 0;
}

uintptr_t RageDisplay_Vulkan::GetRenderTarget()
{
	return m_currentRT;
}

void RageDisplay_Vulkan::SetRenderTarget(uintptr_t /*iHandle*/, bool /*bPreserveTexture*/)
{
	// TODO: implement render-to-texture
}

// ====================================================================
// Compiled geometry
// ====================================================================

RageCompiledGeometry *RageDisplay_Vulkan::CreateCompiledGeometry()
{
	return new RageCompiledGeometryVulkan(&m_ctx);
}

void RageDisplay_Vulkan::DeleteCompiledGeometry(RageCompiledGeometry *p)
{
	delete p;
}

// ====================================================================
// Screenshot
// ====================================================================

RageSurface *RageDisplay_Vulkan::CreateScreenshot()
{
	// TODO: implement via vkCmdCopyImageToBuffer
	return nullptr;
}

/*
 * Copyright (c) 2025 ITGmania Contributors
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, and/or sell copies of the Software, and to permit persons to
 * whom the Software is furnished to do so, provided that the above
 * copyright notice(s) and this permission notice appear in all copies of
 * the Software and that both the above copyright notice(s) and this
 * permission notice appear in supporting documentation.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS
 * INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT
 * OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
 * OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
 * OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 * PERFORMANCE OF THIS SOFTWARE.
 */
